[terminal.shell]
program = "wsl"
args = ["~"]

[[keyboard.bindings]]
key = "Space"

mods = "Control"
chars = "\u0000"

[font]
size = 9
[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
[font.bold]
family = "JetBrainsMono NF"
style = "Bold"
[font.italic]
family = "JetBrainsMono NF"
style = "Italic"
